test go build action

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -2,32 +2,28 @@
 
 set -e
 
-[ -n "$ASDF_INSTALL_VERSION" ] || (echo $'Missing ASDF_INSTALL_VERSION' 1>&2 && exit 1)
-[ -n "$ASDF_DOWNLOAD_PATH" ] || (echo $'Missing ASDF_DOWNLOAD_PATH' 1>&2 && exit 1)
+[ -n "$ASDF_INSTALL_VERSION" ] || (echo $'Missing ASDF_INSTALL_VERSION' 1>&2; exit 1)
+[ -n "$ASDF_DOWNLOAD_PATH" ] || (echo $'Missing ASDF_DOWNLOAD_PATH' 1>&2; exit 1)
 
 command -v go > /dev/null 2>&1 ||
-  (echo $'Could not find go executable. Make sure you have go version $_SUPPORTED_GO_VERSION installed.' 1>&2 && exit 1)
+  (echo $'Could not find go executable. Make sure you have go version $_SUPPORTED_GO_VERSION installed.' 1>&2; exit 1)
 
 _SUPPORTED_GO_VERSION="1.15"
 _INSTALLED_GO_VERSION="$(go version | sed -n "s/.*go\([[:digit:]]\+\.[[:digit:]]\+\).*$/\1/p")"
 
 [ "$_INSTALLED_GO_VERSION" == "$_SUPPORTED_GO_VERSION" ] ||
-  (echo $'mongo-tools needs to be compiled with $_SUPPORTED_GO_VERSION, but you have $_INSTALLED_GO_VERSION installed.' 1>&2 && exit 1)
+  (echo $'mongo-tools needs to be compiled with $_SUPPORTED_GO_VERSION, but you have $_INSTALLED_GO_VERSION installed.' 1>&2; exit 1)
 
 unset _SUPPORTED_GO_VERSION _INSTALLED_GO_VERSION
 
-#[ -n "$GOROOT" ] || (echo $'Missing GOROOT' 1>&2 && exit 1)
-
-export GOPATH=$ASDF_DOWNLOAD_PATH
-#GOBIN=$ASDF_DOWNLOAD_PATH/bin
-
 (
-  mkdir -p "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools" &&
-    curl -fsSL "https://github.com/mongodb/mongo-tools/archive/r$ASDF_INSTALL_VERSION.tar.gz" |
-    tar xzf - -C "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools" --strip-components=1 &&
-    exit 0
+  mkdir -p "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb"
+  git clone --branch "r$ADSF_INSTALL_VERSION" --depth 1 \
+    "https://github.com/mongodb/mongo-tools" \
+    "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools"
+
 ) || (
-  echo $'Download failed' 1>&2 &&
-    rm -rf "$ASDF_DOWNLOAD_PATH" &&
-    exit 1
+  echo $'Download failed' 1>&2
+  rm -rf "$ASDF_DOWNLOAD_PATH"
+  exit 1
 )
diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -9,15 +9,23 @@ set -e
 [ -x "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools/build.sh" ] || . "$(dirname "$0")/download"
 
 (
-  mkdir -p "$ASDF_INSTALL_PATH/bin" &&
-    bash -c "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools/build.sh" &&
-    bash -c "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools/test.sh" &&
-    cp "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools/bin/*" "$ASDF_INSTALL_PATH/bin/" &&
-    rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH" &&
-    echo $'mongo-tools have been installed.' &&
-    exit 0
+  _ppwd="$(pwd)"
+  cd "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools"
+
+  ./build.sh ssl sasl
+  ./test.sh ssl sasl
+
+  mkdir -p "$ASDF_INSTALL_PATH/bin"
+  cp "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools/bin/*" "$ASDF_INSTALL_PATH/bin/"
+  
+  cd $_ppwd
+  unset $_ppwd
+  rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH"
+
+  echo $'mongo-tools have been installed.'
+
 ) || (
-  rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH" &&
-    echo $'An error ocurred while installing mongo-tools $ASDF_INSTALL_VERSION' 1>&2 &&
-    exit 1
+  rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH"
+  echo $'An error ocurred while installing mongo-tools $ASDF_INSTALL_VERSION' 1>&2
+  exit 1
 )
