test go build action

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -3,32 +3,29 @@
 set -e
 
 [ -n "$ASDF_INSTALL_PATH" ] || (
-  echo $'Missing ASDF_INSTALL_PATH' 1>&2
-  exit 1
+  echo $'Missing ASDF_INSTALL_PATH' 1>&2 &&
+    exit 1
 )
 
 [ "$ASDF_INSTALL_TYPE" == "version" ] || (
-  echo $'asdf-mongo-tools supports release installs only' 1>&2
-  exit 1
+  echo $'asdf-mongo-tools supports release installs only' 1>&2 &&
+    exit 1
 )
 
 # shellcheck source=bin/download
 [ -x "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools/build.sh" ] || . "$(dirname "$0")/download"
 
+export GOBIN="$ASDF_INSTALL_PATH/bin"
+[ -n "$GOROOT" ] || export GOROOT="$(go env GOROOT)"
+
 (
-  export GOBIN="$ASDF_INSTALL_PATH/bin"
-  mkdir -p "$ASDF_INSTALL_PATH/bin"
-
-  cd "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools"
-
-  ./build.sh ssl
-  #./test.sh
-  #cp "./bin/*" "$ASDF_INSTALL_PATH/bin/"
-
-  echo $'mongo-tools have been installed.'
+  mkdir -p "$ASDF_INSTALL_PATH/bin" &&
+    cd "$ASDF_DOWNLOAD_PATH/src/github.com/mongodb/mongo-tools" &&
+    ./build.sh ssl &&
+    echo $'mongo-tools have been installed.'
 
 ) || (
-  rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH"
-  echo $'An error ocurred while installing mongo-tools $ASDF_INSTALL_VERSION' 1>&2
-  exit 1
+  rm -rf "$ASDF_INSTALL_PATH" "$ASDF_DOWNLOAD_PATH" &&
+    echo $'An error ocurred while installing mongo-tools $ASDF_INSTALL_VERSION' 1>&2 &&
+    exit 1
 )
